/*
 * This file is generated by jOOQ.
*/
package com.cimc.datahub.mining.jooq.tables.records;


import com.cimc.datahub.mining.jooq.tables.MutualMarketTop10Daily;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MutualMarketTop10DailyRecord extends UpdatableRecordImpl<MutualMarketTop10DailyRecord> implements Record11<Long, Integer, String, String, Long, Long, Long, Date, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 732638890;

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.rank</code>. 排名
     */
    public void setRank(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.rank</code>. 排名
     */
    public Integer getRank() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.stock_code</code>. 股票代码
     */
    public void setStockCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.stock_code</code>. 股票代码
     */
    public String getStockCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.stock_name</code>. 股票名称
     */
    public void setStockName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.stock_name</code>. 股票名称
     */
    public String getStockName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.buy_amount</code>. 买入金额(RMB)
     */
    public void setBuyAmount(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.buy_amount</code>. 买入金额(RMB)
     */
    public Long getBuyAmount() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.sell_amount</code>. 卖出金额(RMB)
     */
    public void setSellAmount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.sell_amount</code>. 卖出金额(RMB)
     */
    public Long getSellAmount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.total_amount</code>. 买入及卖出金额(RMB)
     */
    public void setTotalAmount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.total_amount</code>. 买入及卖出金额(RMB)
     */
    public Long getTotalAmount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.event_date</code>.
     */
    public void setEventDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.event_date</code>.
     */
    public Date getEventDate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.created_date</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.modified_date</code>.
     */
    public void setModifiedDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.modified_date</code>.
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>basedata.mutual_market_top10_daily.flow_type</code>.
     */
    public void setFlowType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>basedata.mutual_market_top10_daily.flow_type</code>.
     */
    public String getFlowType() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Integer, String, String, Long, Long, Long, Date, Timestamp, Timestamp, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Integer, String, String, Long, Long, Long, Date, Timestamp, Timestamp, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.STOCK_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.STOCK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.BUY_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.SELL_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.TOTAL_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.EVENT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.MODIFIED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.FLOW_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStockCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStockName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getBuyAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getSellAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getTotalAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getEventDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFlowType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value2(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value3(String value) {
        setStockCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value4(String value) {
        setStockName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value5(Long value) {
        setBuyAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value6(Long value) {
        setSellAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value7(Long value) {
        setTotalAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value8(Date value) {
        setEventDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value9(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value10(Timestamp value) {
        setModifiedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord value11(String value) {
        setFlowType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10DailyRecord values(Long value1, Integer value2, String value3, String value4, Long value5, Long value6, Long value7, Date value8, Timestamp value9, Timestamp value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MutualMarketTop10DailyRecord
     */
    public MutualMarketTop10DailyRecord() {
        super(MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY);
    }

    /**
     * Create a detached, initialised MutualMarketTop10DailyRecord
     */
    public MutualMarketTop10DailyRecord(Long id, Integer rank, String stockCode, String stockName, Long buyAmount, Long sellAmount, Long totalAmount, Date eventDate, Timestamp createdDate, Timestamp modifiedDate, String flowType) {
        super(MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY);

        set(0, id);
        set(1, rank);
        set(2, stockCode);
        set(3, stockName);
        set(4, buyAmount);
        set(5, sellAmount);
        set(6, totalAmount);
        set(7, eventDate);
        set(8, createdDate);
        set(9, modifiedDate);
        set(10, flowType);
    }
}
