/*
 * This file is generated by jOOQ.
*/
package com.cimc.datahub.mining.jooq;


import com.cimc.datahub.mining.jooq.tables.HkToMainland;
import com.cimc.datahub.mining.jooq.tables.MutualMarketOverviewDaily;
import com.cimc.datahub.mining.jooq.tables.MutualMarketTop10Daily;
import com.cimc.datahub.mining.jooq.tables.SzMarketOverview;
import com.cimc.datahub.mining.jooq.tables.records.HkToMainlandRecord;
import com.cimc.datahub.mining.jooq.tables.records.MutualMarketOverviewDailyRecord;
import com.cimc.datahub.mining.jooq.tables.records.MutualMarketTop10DailyRecord;
import com.cimc.datahub.mining.jooq.tables.records.SzMarketOverviewRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>basedata</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<HkToMainlandRecord, Integer> IDENTITY_HK_TO_MAINLAND = Identities0.IDENTITY_HK_TO_MAINLAND;
    public static final Identity<MutualMarketOverviewDailyRecord, Long> IDENTITY_MUTUAL_MARKET_OVERVIEW_DAILY = Identities0.IDENTITY_MUTUAL_MARKET_OVERVIEW_DAILY;
    public static final Identity<MutualMarketTop10DailyRecord, Long> IDENTITY_MUTUAL_MARKET_TOP10_DAILY = Identities0.IDENTITY_MUTUAL_MARKET_TOP10_DAILY;
    public static final Identity<SzMarketOverviewRecord, Long> IDENTITY_SZ_MARKET_OVERVIEW = Identities0.IDENTITY_SZ_MARKET_OVERVIEW;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HkToMainlandRecord> KEY_HK_TO_MAINLAND_PRIMARY = UniqueKeys0.KEY_HK_TO_MAINLAND_PRIMARY;
    public static final UniqueKey<HkToMainlandRecord> KEY_HK_TO_MAINLAND_EVENT_DATA_CODE_IDX = UniqueKeys0.KEY_HK_TO_MAINLAND_EVENT_DATA_CODE_IDX;
    public static final UniqueKey<MutualMarketOverviewDailyRecord> KEY_MUTUAL_MARKET_OVERVIEW_DAILY_PRIMARY = UniqueKeys0.KEY_MUTUAL_MARKET_OVERVIEW_DAILY_PRIMARY;
    public static final UniqueKey<MutualMarketTop10DailyRecord> KEY_MUTUAL_MARKET_TOP10_DAILY_PRIMARY = UniqueKeys0.KEY_MUTUAL_MARKET_TOP10_DAILY_PRIMARY;
    public static final UniqueKey<SzMarketOverviewRecord> KEY_SZ_MARKET_OVERVIEW_PRIMARY = UniqueKeys0.KEY_SZ_MARKET_OVERVIEW_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<HkToMainlandRecord, Integer> IDENTITY_HK_TO_MAINLAND = createIdentity(HkToMainland.HK_TO_MAINLAND, HkToMainland.HK_TO_MAINLAND.ID);
        public static Identity<MutualMarketOverviewDailyRecord, Long> IDENTITY_MUTUAL_MARKET_OVERVIEW_DAILY = createIdentity(MutualMarketOverviewDaily.MUTUAL_MARKET_OVERVIEW_DAILY, MutualMarketOverviewDaily.MUTUAL_MARKET_OVERVIEW_DAILY.ID);
        public static Identity<MutualMarketTop10DailyRecord, Long> IDENTITY_MUTUAL_MARKET_TOP10_DAILY = createIdentity(MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY, MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.ID);
        public static Identity<SzMarketOverviewRecord, Long> IDENTITY_SZ_MARKET_OVERVIEW = createIdentity(SzMarketOverview.SZ_MARKET_OVERVIEW, SzMarketOverview.SZ_MARKET_OVERVIEW.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<HkToMainlandRecord> KEY_HK_TO_MAINLAND_PRIMARY = createUniqueKey(HkToMainland.HK_TO_MAINLAND, "KEY_hk_to_mainland_PRIMARY", HkToMainland.HK_TO_MAINLAND.ID);
        public static final UniqueKey<HkToMainlandRecord> KEY_HK_TO_MAINLAND_EVENT_DATA_CODE_IDX = createUniqueKey(HkToMainland.HK_TO_MAINLAND, "KEY_hk_to_mainland_event_data_code_idx", HkToMainland.HK_TO_MAINLAND.CODE, HkToMainland.HK_TO_MAINLAND.EVENT_DATE);
        public static final UniqueKey<MutualMarketOverviewDailyRecord> KEY_MUTUAL_MARKET_OVERVIEW_DAILY_PRIMARY = createUniqueKey(MutualMarketOverviewDaily.MUTUAL_MARKET_OVERVIEW_DAILY, "KEY_mutual_market_overview_daily_PRIMARY", MutualMarketOverviewDaily.MUTUAL_MARKET_OVERVIEW_DAILY.ID);
        public static final UniqueKey<MutualMarketTop10DailyRecord> KEY_MUTUAL_MARKET_TOP10_DAILY_PRIMARY = createUniqueKey(MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY, "KEY_mutual_market_top10_daily_PRIMARY", MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY.ID);
        public static final UniqueKey<SzMarketOverviewRecord> KEY_SZ_MARKET_OVERVIEW_PRIMARY = createUniqueKey(SzMarketOverview.SZ_MARKET_OVERVIEW, "KEY_sz_market_overview_PRIMARY", SzMarketOverview.SZ_MARKET_OVERVIEW.ID);
    }
}
