/*
 * This file is generated by jOOQ.
*/
package com.cimc.datahub.mining.jooq;


import com.cimc.datahub.mining.jooq.tables.HkToMainland;
import com.cimc.datahub.mining.jooq.tables.MutualMarketOverviewDaily;
import com.cimc.datahub.mining.jooq.tables.MutualMarketTop10Daily;
import com.cimc.datahub.mining.jooq.tables.SzMarketOverview;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in basedata
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>basedata.hk_to_mainland</code>.
     */
    public static final HkToMainland HK_TO_MAINLAND = com.cimc.datahub.mining.jooq.tables.HkToMainland.HK_TO_MAINLAND;

    /**
     * The table <code>basedata.mutual_market_overview_daily</code>.
     */
    public static final MutualMarketOverviewDaily MUTUAL_MARKET_OVERVIEW_DAILY = com.cimc.datahub.mining.jooq.tables.MutualMarketOverviewDaily.MUTUAL_MARKET_OVERVIEW_DAILY;

    /**
     * The table <code>basedata.mutual_market_top10_daily</code>.
     */
    public static final MutualMarketTop10Daily MUTUAL_MARKET_TOP10_DAILY = com.cimc.datahub.mining.jooq.tables.MutualMarketTop10Daily.MUTUAL_MARKET_TOP10_DAILY;

    /**
     * The table <code>basedata.sz_market_overview</code>.
     */
    public static final SzMarketOverview SZ_MARKET_OVERVIEW = com.cimc.datahub.mining.jooq.tables.SzMarketOverview.SZ_MARKET_OVERVIEW;
}
