/*
 * This file is generated by jOOQ.
*/
package com.cimc.datahub.mining.jooq.tables;


import com.cimc.datahub.mining.jooq.Basedata;
import com.cimc.datahub.mining.jooq.Keys;
import com.cimc.datahub.mining.jooq.tables.records.MutualMarketOverviewDailyRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MutualMarketOverviewDaily extends TableImpl<MutualMarketOverviewDailyRecord> {

    private static final long serialVersionUID = -1193014673;

    /**
     * The reference instance of <code>basedata.mutual_market_overview_daily</code>
     */
    public static final MutualMarketOverviewDaily MUTUAL_MARKET_OVERVIEW_DAILY = new MutualMarketOverviewDaily();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MutualMarketOverviewDailyRecord> getRecordType() {
        return MutualMarketOverviewDailyRecord.class;
    }

    /**
     * The column <code>basedata.mutual_market_overview_daily.id</code>.
     */
    public final TableField<MutualMarketOverviewDailyRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>basedata.mutual_market_overview_daily.total_amount</code>. 买入及卖出成交额 (RMB mil)
     */
    public final TableField<MutualMarketOverviewDailyRecord, Double> TOTAL_AMOUNT = createField("total_amount", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "买入及卖出成交额 (RMB mil)");

    /**
     * The column <code>basedata.mutual_market_overview_daily.buy_amount</code>. 买入成交额 (RMB mil)
     */
    public final TableField<MutualMarketOverviewDailyRecord, Double> BUY_AMOUNT = createField("buy_amount", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "买入成交额 (RMB mil)");

    /**
     * The column <code>basedata.mutual_market_overview_daily.sell_amount</code>. 卖出成交额 (RMB mil)
     */
    public final TableField<MutualMarketOverviewDailyRecord, Double> SELL_AMOUNT = createField("sell_amount", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "卖出成交额 (RMB mil)");

    /**
     * The column <code>basedata.mutual_market_overview_daily.total_count</code>. 买入及卖出成交数目
     */
    public final TableField<MutualMarketOverviewDailyRecord, Long> TOTAL_COUNT = createField("total_count", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "买入及卖出成交数目");

    /**
     * The column <code>basedata.mutual_market_overview_daily.buy_count</code>. 买入成交数目
     */
    public final TableField<MutualMarketOverviewDailyRecord, Long> BUY_COUNT = createField("buy_count", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "买入成交数目");

    /**
     * The column <code>basedata.mutual_market_overview_daily.sell_count</code>. 卖出成交数目
     */
    public final TableField<MutualMarketOverviewDailyRecord, Long> SELL_COUNT = createField("sell_count", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "卖出成交数目");

    /**
     * The column <code>basedata.mutual_market_overview_daily.dqb</code>. 每日额度余额(RMB mil)
     */
    public final TableField<MutualMarketOverviewDailyRecord, Double> DQB = createField("dqb", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "每日额度余额(RMB mil)");

    /**
     * The column <code>basedata.mutual_market_overview_daily.dqb_percentage</code>. 每日额度余额(%)
     */
    public final TableField<MutualMarketOverviewDailyRecord, Double> DQB_PERCENTAGE = createField("dqb_percentage", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "每日额度余额(%)");

    /**
     * The column <code>basedata.mutual_market_overview_daily.event_date</code>.
     */
    public final TableField<MutualMarketOverviewDailyRecord, Date> EVENT_DATE = createField("event_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>basedata.mutual_market_overview_daily.created_date</code>.
     */
    public final TableField<MutualMarketOverviewDailyRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>basedata.mutual_market_overview_daily.modified_date</code>.
     */
    public final TableField<MutualMarketOverviewDailyRecord, Timestamp> MODIFIED_DATE = createField("modified_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>basedata.mutual_market_overview_daily.flow_type</code>.
     */
    public final TableField<MutualMarketOverviewDailyRecord, String> FLOW_TYPE = createField("flow_type", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * Create a <code>basedata.mutual_market_overview_daily</code> table reference
     */
    public MutualMarketOverviewDaily() {
        this("mutual_market_overview_daily", null);
    }

    /**
     * Create an aliased <code>basedata.mutual_market_overview_daily</code> table reference
     */
    public MutualMarketOverviewDaily(String alias) {
        this(alias, MUTUAL_MARKET_OVERVIEW_DAILY);
    }

    private MutualMarketOverviewDaily(String alias, Table<MutualMarketOverviewDailyRecord> aliased) {
        this(alias, aliased, null);
    }

    private MutualMarketOverviewDaily(String alias, Table<MutualMarketOverviewDailyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Basedata.BASEDATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MutualMarketOverviewDailyRecord, Long> getIdentity() {
        return Keys.IDENTITY_MUTUAL_MARKET_OVERVIEW_DAILY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MutualMarketOverviewDailyRecord> getPrimaryKey() {
        return Keys.KEY_MUTUAL_MARKET_OVERVIEW_DAILY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MutualMarketOverviewDailyRecord>> getKeys() {
        return Arrays.<UniqueKey<MutualMarketOverviewDailyRecord>>asList(Keys.KEY_MUTUAL_MARKET_OVERVIEW_DAILY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketOverviewDaily as(String alias) {
        return new MutualMarketOverviewDaily(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MutualMarketOverviewDaily rename(String name) {
        return new MutualMarketOverviewDaily(name, null);
    }
}
