/*
 * This file is generated by jOOQ.
*/
package com.cimc.datahub.mining.jooq.tables;


import com.cimc.datahub.mining.jooq.Basedata;
import com.cimc.datahub.mining.jooq.Keys;
import com.cimc.datahub.mining.jooq.tables.records.MutualMarketTop10DailyRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MutualMarketTop10Daily extends TableImpl<MutualMarketTop10DailyRecord> {

    private static final long serialVersionUID = -1074265670;

    /**
     * The reference instance of <code>basedata.mutual_market_top10_daily</code>
     */
    public static final MutualMarketTop10Daily MUTUAL_MARKET_TOP10_DAILY = new MutualMarketTop10Daily();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MutualMarketTop10DailyRecord> getRecordType() {
        return MutualMarketTop10DailyRecord.class;
    }

    /**
     * The column <code>basedata.mutual_market_top10_daily.id</code>.
     */
    public final TableField<MutualMarketTop10DailyRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>basedata.mutual_market_top10_daily.rank</code>. 排名
     */
    public final TableField<MutualMarketTop10DailyRecord, Integer> RANK = createField("rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "排名");

    /**
     * The column <code>basedata.mutual_market_top10_daily.stock_code</code>. 股票代码
     */
    public final TableField<MutualMarketTop10DailyRecord, String> STOCK_CODE = createField("stock_code", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "股票代码");

    /**
     * The column <code>basedata.mutual_market_top10_daily.stock_name</code>. 股票名称
     */
    public final TableField<MutualMarketTop10DailyRecord, String> STOCK_NAME = createField("stock_name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "股票名称");

    /**
     * The column <code>basedata.mutual_market_top10_daily.buy_amount</code>. 买入金额(RMB)
     */
    public final TableField<MutualMarketTop10DailyRecord, Long> BUY_AMOUNT = createField("buy_amount", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "买入金额(RMB)");

    /**
     * The column <code>basedata.mutual_market_top10_daily.sell_amount</code>. 卖出金额(RMB)
     */
    public final TableField<MutualMarketTop10DailyRecord, Long> SELL_AMOUNT = createField("sell_amount", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "卖出金额(RMB)");

    /**
     * The column <code>basedata.mutual_market_top10_daily.total_amount</code>. 买入及卖出金额(RMB)
     */
    public final TableField<MutualMarketTop10DailyRecord, Long> TOTAL_AMOUNT = createField("total_amount", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "买入及卖出金额(RMB)");

    /**
     * The column <code>basedata.mutual_market_top10_daily.event_date</code>.
     */
    public final TableField<MutualMarketTop10DailyRecord, Date> EVENT_DATE = createField("event_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>basedata.mutual_market_top10_daily.created_date</code>.
     */
    public final TableField<MutualMarketTop10DailyRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>basedata.mutual_market_top10_daily.modified_date</code>.
     */
    public final TableField<MutualMarketTop10DailyRecord, Timestamp> MODIFIED_DATE = createField("modified_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>basedata.mutual_market_top10_daily.flow_type</code>.
     */
    public final TableField<MutualMarketTop10DailyRecord, String> FLOW_TYPE = createField("flow_type", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * Create a <code>basedata.mutual_market_top10_daily</code> table reference
     */
    public MutualMarketTop10Daily() {
        this("mutual_market_top10_daily", null);
    }

    /**
     * Create an aliased <code>basedata.mutual_market_top10_daily</code> table reference
     */
    public MutualMarketTop10Daily(String alias) {
        this(alias, MUTUAL_MARKET_TOP10_DAILY);
    }

    private MutualMarketTop10Daily(String alias, Table<MutualMarketTop10DailyRecord> aliased) {
        this(alias, aliased, null);
    }

    private MutualMarketTop10Daily(String alias, Table<MutualMarketTop10DailyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Basedata.BASEDATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MutualMarketTop10DailyRecord, Long> getIdentity() {
        return Keys.IDENTITY_MUTUAL_MARKET_TOP10_DAILY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MutualMarketTop10DailyRecord> getPrimaryKey() {
        return Keys.KEY_MUTUAL_MARKET_TOP10_DAILY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MutualMarketTop10DailyRecord>> getKeys() {
        return Arrays.<UniqueKey<MutualMarketTop10DailyRecord>>asList(Keys.KEY_MUTUAL_MARKET_TOP10_DAILY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutualMarketTop10Daily as(String alias) {
        return new MutualMarketTop10Daily(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MutualMarketTop10Daily rename(String name) {
        return new MutualMarketTop10Daily(name, null);
    }
}
